from pathlib import Path
from datetime import datetime
from collections import defaultdict
from typing import Dict, List, Any
import html


# Translation dictionaries
TRANSLATIONS = {
    'en': {
        'title': 'Content Analysis Report',
        'generated': 'Generated',
        'language': 'Language',
        'files_scanned': 'Files Scanned',
        'files_with_hits': 'Files with Hits',
        'total_matches': 'Total Matches',
        'unique_terms': 'Unique Terms',
        'categories': 'Categories',
        'categories_overview': 'Categories Overview',
        'category': 'Category',
        'total_occurrences': 'Total Occurrences',
        'top_terms': 'Top Terms',
        'no_sensitive_terms': 'No sensitive terms found in any category',
        'detailed_file_results': 'Detailed File Results',
        'show_clean_files': 'Show Clean Files',
        'hide_clean_files': 'Hide Clean Files',
        'clean': 'Clean',
        'matches': 'matches',
        'view_file': 'View File',
        'no_findings': 'No sensitive terms found in this file',
        'occurrences': 'Occurrences',
        'pages': 'Page(s)',
        'context': 'Context (page',
        'generated_by': 'Generated by Content Analyzer',
        'file_types_analyzed': 'File Types Analyzed',
        'files': 'files',
    },
    'cz': {
        'title': 'Zpráva o analýze obsahu',
        'generated': 'Vygenerováno',
        'language': 'Jazyk',
        'files_scanned': 'Prohledané soubory',
        'files_with_hits': 'Soubory se záznamy',
        'total_matches': 'Celkem záznamů',
        'unique_terms': 'Unikátní termíny',
        'categories': 'Kategorie',
        'categories_overview': 'Přehled kategorií',
        'category': 'Kategorie',
        'total_occurrences': 'Celkem výskytů',
        'top_terms': 'Nejčastější termíny',
        'no_sensitive_terms': 'V žádné kategorii nebyly nalezeny citlivé termíny',
        'detailed_file_results': 'Podrobné výsledky souborů',
        'show_clean_files': 'Zobrazit čisté soubory',
        'hide_clean_files': 'Skrýt čisté soubory',
        'clean': 'Čistý',
        'matches': 'záznamů',
        'view_file': 'Zobrazit soubor',
        'no_findings': 'V tomto souboru nebyly nalezeny citlivé termíny',
        'occurrences': 'Výskyty',
        'pages': 'Strana/y',
        'context': 'Kontext (strana',
        'generated_by': 'Vygenerováno nástrojem Content Analyzer',
        'file_types_analyzed': 'Analyzované typy souborů',
        'files': 'souborů',
    }
}


def escape_html(text: str) -> str:
    return html.escape(text)


def get_translation(lang: str, key: str) -> str:
    """Get translated text for a given key."""
    return TRANSLATIONS.get(lang, TRANSLATIONS['en']).get(key, key)


def generate_html_report(
    scan_results: List[Dict[str, Any]],
    global_stats: Dict[str, Dict[str, int]],
    output_path: Path,
    sensitivity_list: str,
    total_files: int,
    files_with_hits: int,
    total_matches: int,
    file_types: Dict[str, int],
    report_lang: str = "en"
) -> None:

    html_content = _generate_html_structure(
        scan_results,
        global_stats,
        sensitivity_list,
        total_files,
        files_with_hits,
        total_matches,
        file_types,
        report_lang
    )

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html_content)


def _generate_html_structure(
    scan_results: List[Dict[str, Any]],
    global_stats: Dict[str, Dict[str, int]],
    sensitivity_list: str,
    total_files: int,
    files_with_hits: int,
    total_matches: int,
    file_types: Dict[str, int],
    report_lang: str
) -> str:

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    t = lambda key: get_translation(report_lang, key)

    html = f"""<!DOCTYPE html>
<html lang="{report_lang}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{t('title')}</title>
    <style>
        {_get_css_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{t('title')}</h1>
            <div class="header-info">
                <div class="info-item">
                    <span class="info-label">{t('generated')}:</span>
                    <span class="info-value">{timestamp}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">{t('language')}:</span>
                    <span class="info-value">{sensitivity_list.upper()}</span>
                </div>
            </div>
            {_generate_summary_section(global_stats, total_files, files_with_hits, total_matches, report_lang)}
            {_generate_file_types_section(file_types, report_lang)}
        </header>

        {_generate_categories_overview(global_stats, report_lang)}

        {_generate_files_section(scan_results, report_lang)}

        <footer>
            <p>{t('generated_by')} | © {datetime.now().year}</p>
        </footer>
    </div>

    <script>
        {_get_javascript(report_lang)}
    </script>
</body>
</html>"""

    return html


def _get_css_styles() -> str:
    """Return the CSS styles for the report."""
    return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background: #f5f5f5;
            min-height: 100vh;
            padding: 0;
            color: #0c0c14;
        }

        .container {
            max-width: 1600px;
            margin: 0 auto;
            background: white;
        }

        header {
            background: linear-gradient(135deg, #f0f9f9 0%, #e0f4f4 100%);
            color: #0c0c14;
            padding: 32px 48px 48px;
            border-bottom: 3px solid #219b95;
        }

        header h1 {
            font-size: 1.75em;
            font-weight: 600;
            letter-spacing: -0.5px;
            margin: 0;
            color: #0c0c14;
        }

        .header-info {
            display: flex;
            gap: 24px;
            margin-top: 12px;
            font-size: 0.9em;
            color: #666;
        }

        .info-item {
            display: flex;
            gap: 6px;
        }

        .info-label {
            font-weight: 500;
        }

        .info-value {
            font-weight: 600;
            color: #0c0c14;
        }

        .header-summary {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: 16px;
            margin-top: 32px;
        }

        .header-summary-card {
            background: white;
            border-left: 3px solid #219b95;
            padding: 20px;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
            display: flex;
            flex-direction: column;
            gap: 6px;
        }

        .header-summary-card h3 {
            font-size: 2em;
            font-weight: 700;
            color: #219b95;
            margin: 0;
            line-height: 1;
        }

        .header-summary-card p {
            font-size: 0.8em;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            font-weight: 500;
            margin: 0;
        }

        .file-types-section {
            margin-top: 24px;
            padding: 16px 20px;
            background: rgba(255, 255, 255, 0.7);
            border-radius: 4px;
            border: 1px solid rgba(33, 155, 149, 0.2);
        }

        .file-types-title {
            font-size: 0.85em;
            color: #219b95;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            font-weight: 600;
            margin: 0 0 12px 0;
        }

        .file-types-list {
            display: flex;
            flex-wrap: wrap;
            gap: 8px;
        }

        .file-type-badge {
            display: inline-flex;
            align-items: center;
            overflow: hidden;
            border-radius: 3px;
            font-size: 0.85em;
            box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
        }

        .file-type-badge .ext {
            background: #219b95;
            color: white;
            padding: 6px 10px;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 0.9em;
        }

        .file-type-badge .count {
            background: white;
            color: #0c0c14;
            padding: 6px 10px;
            font-weight: 600;
            border: 1px solid #e6e6e6;
            border-left: none;
        }

        .section {
            padding: 32px 48px;
            border-bottom: 1px solid #e6e6e6;
            background: #fafafa;
        }

        .section:nth-child(even) {
            background: white;
        }

        .section-title {
            font-size: 1.25em;
            color: #0c0c14;
            margin-bottom: 24px;
            font-weight: 600;
            letter-spacing: -0.3px;
            display: flex;
            align-items: center;
            gap: 8px;
        }

        .section-title::before {
            content: '';
            width: 4px;
            height: 24px;
            background: #219b95;
        }

        .section-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 24px;
        }

        .toggle-clean-btn {
            background: #f5f5f5;
            border: 1px solid #d0d0d0;
            color: #0c0c14;
            padding: 10px 20px;
            font-size: 0.85em;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.2s ease;
            text-transform: uppercase;
            letter-spacing: 0.3px;
        }

        .toggle-clean-btn:hover {
            background: #219b95;
            color: white;
            border-color: #219b95;
        }

        .file-card.clean-file {
            display: none;
        }

        .file-card.clean-file.show {
            display: block;
        }

        .summary-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 16px;
        }

        .summary-card {
            background: white;
            border: 1px solid #d0d0d0;
            padding: 24px;
            transition: all 0.2s ease;
        }

        .summary-card:hover {
            border-color: #219b95;
            box-shadow: 0 2px 8px rgba(33, 155, 149, 0.1);
        }

        .summary-card h3 {
            font-size: 2.25em;
            font-weight: 700;
            color: #219b95;
            margin-bottom: 8px;
            line-height: 1;
        }

        .summary-card p {
            font-size: 0.875em;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            font-weight: 500;
        }

        .category-table {
            width: 100%;
            border-collapse: separate;
            border-spacing: 0;
            background: white;
            border: 1px solid #d0d0d0;
        }

        .category-table th {
            background: #0c0c14;
            color: #e6e6e6;
            padding: 16px 20px;
            text-align: left;
            font-weight: 600;
            font-size: 0.875em;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        .category-table td {
            padding: 16px 20px;
            border-bottom: 1px solid #e6e6e6;
            color: #0c0c14;
        }

        .category-table tbody tr:hover {
            background: #f9f9f9;
        }

        .category-table tbody tr:last-child td {
            border-bottom: none;
        }

        .category-badge {
            display: inline-block;
            background: #219b95;
            color: white;
            padding: 6px 14px;
            font-size: 0.8em;
            font-weight: 600;
            letter-spacing: 0.3px;
        }

        .count-badge {
            display: inline-block;
            background: #0c0c14;
            color: white;
            padding: 6px 14px;
            font-weight: 600;
            min-width: 50px;
            text-align: center;
            font-size: 0.875em;
        }

        .term-badge {
            display: inline-flex;
            margin-right: 8px;
            margin-bottom: 4px;
            overflow: hidden;
            font-size: 0.85em;
        }

        .term-word {
            background: #219b95;
            color: white;
            padding: 6px 10px;
            font-weight: 600;
        }

        .term-count {
            background: #0c0c14;
            color: white;
            padding: 6px 10px;
            font-weight: 600;
            min-width: 30px;
            text-align: center;
        }

        .file-card {
            background: white;
            border: 1px solid #d0d0d0;
            margin-bottom: 16px;
            transition: all 0.2s ease;
        }

        .file-card:hover {
            border-color: #219b95;
            box-shadow: 0 2px 8px rgba(33, 155, 149, 0.1);
        }

        .file-card-header {
            background: white;
            border-bottom: 1px solid #e6e6e6;
            padding: 20px 24px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            cursor: pointer;
        }

        .file-card-header h3 {
            font-size: 0.95em;
            font-weight: 600;
            color: #0c0c14;
            display: flex;
            align-items: center;
            gap: 12px;
        }

        .file-link {
            color: #219b95;
            text-decoration: none;
            padding: 8px 16px;
            background: rgba(33, 155, 149, 0.1);
            font-size: 0.85em;
            font-weight: 600;
            transition: all 0.2s ease;
            text-transform: uppercase;
            letter-spacing: 0.3px;
        }

        .file-link:hover {
            background: #219b95;
            color: white;
        }

        .file-card-body {
            padding: 24px;
            display: none;
            background: #f9f9f9;
        }

        .file-card-body.active {
            display: block;
        }

        .category-section {
            margin-bottom: 24px;
            padding: 0;
        }

        .category-section h4 {
            color: #0c0c14;
            margin-bottom: 16px;
            font-size: 1em;
            font-weight: 600;
            padding-bottom: 8px;
            border-bottom: 2px solid #219b95;
        }

        .match-item {
            background: white;
            padding: 16px;
            margin-bottom: 12px;
            border-left: 3px solid #219b95;
        }

        .match-word {
            font-weight: 600;
            color: #0c0c14;
            font-size: 1em;
            margin-bottom: 10px;
        }

        .match-details {
            display: flex;
            gap: 24px;
            margin-bottom: 12px;
            font-size: 0.85em;
            color: #666;
        }

        .context {
            background: #f5f5f5;
            padding: 12px;
            font-family: 'SF Mono', 'Consolas', 'Monaco', monospace;
            font-size: 0.85em;
            overflow-x: auto;
            border-left: 2px solid #219b95;
            border: 1px solid #e6e6e6;
        }

        .context-match {
            background: #219b95;
            color: white;
            font-weight: 600;
            padding: 2px 6px;
        }

        .no-findings {
            text-align: center;
            padding: 32px;
            color: #219b95;
            font-size: 1em;
            font-weight: 500;
        }

        .toggle-icon {
            transition: transform 0.2s ease;
            color: #219b95;
            font-size: 0.7em;
        }

        .toggle-icon.active {
            transform: rotate(90deg);
        }

        footer {
            background: #0c0c14;
            color: #e6e6e6;
            text-align: center;
            padding: 24px;
            font-size: 0.85em;
        }

        .status-clean {
            color: #219b95;
            font-weight: 600;
            font-size: 0.875em;
            text-transform: uppercase;
            letter-spacing: 0.3px;
        }

        .status-warning {
            color: #e67e22;
            font-weight: 600;
            font-size: 0.875em;
            text-transform: uppercase;
            letter-spacing: 0.3px;
        }

        .status-danger {
            color: #c0392b;
            font-weight: 600;
            font-size: 0.875em;
            text-transform: uppercase;
            letter-spacing: 0.3px;
        }

        @media (max-width: 768px) {
            header, .section {
                padding: 24px;
            }

            .header-info {
                flex-direction: column;
                gap: 8px;
            }

            .header-summary {
                grid-template-columns: 1fr;
            }

            .file-card-header {
                flex-direction: column;
                gap: 12px;
                align-items: flex-start;
            }

            .match-details {
                flex-direction: column;
                gap: 8px;
            }
        }
    """


def _get_javascript(report_lang: str) -> str:
    """Return JavaScript for interactive features."""
    t = lambda key: get_translation(report_lang, key)

    return f"""
        // Toggle file card details
        document.querySelectorAll('.file-card-header').forEach(header => {{
            header.addEventListener('click', (e) => {{
                if (e.target.tagName === 'A') return;

                const body = header.nextElementSibling;
                const icon = header.querySelector('.toggle-icon');

                body.classList.toggle('active');
                icon.classList.toggle('active');
            }});
        }});

        // Toggle clean files visibility
        const toggleBtn = document.getElementById('toggle-clean-files');
        if (toggleBtn) {{
            const originalText = toggleBtn.textContent;
            const cleanCount = originalText.match(/\\((\\d+)\\)/)?.[1] || '';

            toggleBtn.addEventListener('click', () => {{
                const cleanFiles = document.querySelectorAll('.file-card.clean-file');
                const isShowing = cleanFiles[0]?.classList.contains('show');

                cleanFiles.forEach(file => {{
                    file.classList.toggle('show');
                }});

                toggleBtn.textContent = isShowing ? '{t("show_clean_files")} (' + cleanCount + ')' : '{t("hide_clean_files")} (' + cleanCount + ')';
            }});
        }}

        // Smooth scroll to sections
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {{
            anchor.addEventListener('click', function (e) {{
                e.preventDefault();
                const target = document.querySelector(this.getAttribute('href'));
                if (target) {{
                    target.scrollIntoView({{ behavior: 'smooth', block: 'start' }});
                }}
            }});
        }});
    """


def _generate_file_types_section(file_types: Dict[str, int], report_lang: str) -> str:
    """Generate a compact file types breakdown section."""
    t = lambda key: get_translation(report_lang, key)

    if not file_types:
        return ""

    # Sort by count descending
    sorted_types = sorted(file_types.items(), key=lambda x: x[1], reverse=True)

    badges_html = []
    for ext, count in sorted_types:
        badges_html.append(f'<span class="file-type-badge"><span class="ext">{ext}</span><span class="count">{count}</span></span>')

    return f"""
            <div class="file-types-section">
                <h3 class="file-types-title">{t('file_types_analyzed')}</h3>
                <div class="file-types-list">
                    {' '.join(badges_html)}
                </div>
            </div>
    """


def _generate_summary_section(
    global_stats: Dict[str, Dict[str, int]],
    total_files: int,
    files_with_hits: int,
    total_matches: int,
    report_lang: str
) -> str:
    """Generate the summary section within the header."""

    unique_terms = sum(len(words) for words in global_stats.values())
    categories_count = len(global_stats)
    t = lambda key: get_translation(report_lang, key)

    return f"""
            <div class="header-summary">
                <div class="header-summary-card">
                    <h3>{total_files}</h3>
                    <p>{t('files_scanned')}</p>
                </div>
                <div class="header-summary-card">
                    <h3>{files_with_hits}</h3>
                    <p>{t('files_with_hits')}</p>
                </div>
                <div class="header-summary-card">
                    <h3>{total_matches}</h3>
                    <p>{t('total_matches')}</p>
                </div>
                <div class="header-summary-card">
                    <h3>{unique_terms}</h3>
                    <p>{t('unique_terms')}</p>
                </div>
                <div class="header-summary-card">
                    <h3>{categories_count}</h3>
                    <p>{t('categories')}</p>
                </div>
            </div>
    """


def _generate_categories_overview(global_stats: Dict[str, Dict[str, int]], report_lang: str) -> str:
    """Generate categories overview table."""

    t = lambda key: get_translation(report_lang, key)

    if not global_stats:
        return f"""
        <section class="section">
            <h2 class="section-title">{t('categories_overview')}</h2>
            <p class="status-clean">{t('no_sensitive_terms')}</p>
        </section>
        """

    table_rows = []
    for category in sorted(global_stats.keys()):
        words = global_stats[category]
        total_count = sum(words.values())
        unique_count = len(words)

        # Get top 3 words
        top_words = sorted(words.items(), key=lambda x: x[1], reverse=True)[:3]
        top_words_html = " ".join([
            f'<span class="term-badge"><span class="term-word">{escape_html(word)}</span><span class="term-count">{count}</span></span>'
            for word, count in top_words
        ])

        table_rows.append(f"""
            <tr>
                <td><span class="category-badge">{escape_html(category)}</span></td>
                <td><span class="count-badge">{unique_count}</span></td>
                <td><span class="count-badge">{total_count}</span></td>
                <td>{top_words_html}</td>
            </tr>
        """)

    return f"""
        <section class="section" id="categories">
            <h2 class="section-title">{t('categories_overview')}</h2>
            <table class="category-table">
                <thead>
                    <tr>
                        <th>{t('category')}</th>
                        <th>{t('unique_terms')}</th>
                        <th>{t('total_occurrences')}</th>
                        <th>{t('top_terms')}</th>
                    </tr>
                </thead>
                <tbody>
                    {''.join(table_rows)}
                </tbody>
            </table>
        </section>
    """


def _generate_files_section(scan_results: List[Dict[str, Any]], report_lang: str) -> str:
    """Generate the files section with detailed findings."""

    t = lambda key: get_translation(report_lang, key)
    files_html = []
    clean_count = 0

    for item in scan_results:
        file_path = item['file_path']
        results = item['results']

        file_name = Path(file_path).name
        file_uri = Path(file_path).as_uri()

        is_clean = not results
        clean_class = ' clean-file' if is_clean else ''

        if is_clean:
            clean_count += 1
            status = f'<span class="status-clean">{t("clean")}</span>'
            body_content = f'<p class="no-findings">{t("no_findings")}</p>'
        else:
            match_count = sum(len(data['pages']) for category in results.values() for data in category.values())
            status = f'<span class="status-danger">{match_count} {t("matches")}</span>'
            body_content = _generate_file_findings(results, report_lang)

        files_html.append(f"""
            <div class="file-card{clean_class}">
                <div class="file-card-header">
                    <h3>
                        <span class="toggle-icon">▶</span>
                        {escape_html(file_name)}
                    </h3>
                    <div style="display: flex; gap: 15px; align-items: center;">
                        {status}
                        <a href="{file_uri}" class="file-link" title="{t('view_file')}">{t('view_file')}</a>
                    </div>
                </div>
                <div class="file-card-body">
                    {body_content}
                </div>
            </div>
        """)

    toggle_button = ''
    if clean_count > 0:
        toggle_button = f'<button id="toggle-clean-files" class="toggle-clean-btn">{t("show_clean_files")} ({clean_count})</button>'

    return f"""
        <section class="section" id="files">
            <div class="section-header">
                <h2 class="section-title">{t('detailed_file_results')}</h2>
                {toggle_button}
            </div>
            {''.join(files_html)}
        </section>
    """


def _generate_file_findings(results: Dict[str, Dict[str, Any]], report_lang: str) -> str:
    """Generate findings for a specific file."""

    t = lambda key: get_translation(report_lang, key)
    findings_html = []

    for category in sorted(results.keys()):
        words_dict = results[category]

        matches_html = []
        for word in sorted(words_dict.keys()):
            data = words_dict[word]
            pages = sorted(set(data['pages']))
            pages_str = ", ".join(map(str, pages))
            count = len(data['pages'])

            # Get context
            context_html = ""
            if data['contexts']:
                ctx = data['contexts'][0]
                context_html = f"""
                    <div class="context">
                        {escape_html(ctx['before'])}<span class="context-match">{escape_html(ctx['matched'])}</span>{escape_html(ctx['after'])}
                    </div>
                """

            matches_html.append(f"""
                <div class="match-item">
                    <div class="match-word">"{escape_html(word)}"</div>
                    <div class="match-details">
                        <span>{t('occurrences')}: {count}</span>
                        <span>{t('pages')}: {pages_str}</span>
                    </div>
                    {context_html}
                </div>
            """)

        findings_html.append(f"""
            <div class="category-section">
                <h4>{escape_html(category)}</h4>
                {''.join(matches_html)}
            </div>
        """)

    return ''.join(findings_html)
